@DropShield_Api_HostAddress = http://localhost:5257

GET {{DropShield_Api_HostAddress}}/health
Accept: application/json

###

GET {{DropShield_Api_HostAddress}}/internal/metrics
Accept: application/json

###

POST {{DropShield_Api_HostAddress}}/internal/metrics/reset

###
